### ISSUE TITLE
Add fallback support

### ISSUE THREAD

**Issue by JacobDB** [Lehoczky/postcss-fluid#7]
An option to include a fallback for browsers that don't support `clamp` would be nice. Settings could include outputting the `min value` or `max value` only, an average of the two, or output media queries for both (i.e. jump instead of scale).

**Comment by Lehoczky** [comment]
Hi there 👋 

You can use [postcss-preset-env](https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env) in combination with this plugin to convert modern CSS syntax for older browsers.

If you get it working, we can add this to the README.

**Comment by Lehoczky** [comment]
Upon some investigation, it look like the [postcss-clamp](https://github.com/polemius/postcss-clamp) plugin has trouble converting complex `clamp` declarations like what this library produces.

Manually implementing something like you suggested, could work, but that would increase the bundle size of this library, so for now I consider only supporting "modern" (`clamp` is really widely supported) browsers.
